name: CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & run tests
        run: ./gradlew clean build

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/**

  docker-deploy:
    name: Docker Build & Run JAR
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --file Dockerfile --tag java-gradle:${{ github.sha }} .

      - name: Run container & Smoke-test
        run: |
          docker run -d --rm -p 8080:8080 --name sb-test java-gradle:${{ github.sha }}
          echo "Waiting for application to start…"
          for i in {1..50}; do
            if curl -fs http://localhost:8080/ping > /dev/null; then
              echo "Service is up"; exit 0
            fi
            sleep 2
          done
          echo "Service did not start in time" >&2
          docker logs sb-test || true  
          exit 1